VietNameRailway/VietNameRailway/Models/Booking.cs
using System.Diagnostics.CodeAnalysis;

namespace VietNameRailway.Models
{
    public class Booking
    {
        [AllowNull]
        public ICollection<Train>? TauDis {  get; set; }
        public string? TauVes {  get; set; }
        public string? BookingCode { get; set; }
        public bool CaptchaStatus { get; set; }
        public string? TauDiAlias {  get; set; }
        public string? TauVeAlias { get; set; }

    }
}

VietNameRailway/VietNameRailway/Models/Carriages.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace VietNameRailway.Models
{
    public class Carriages
    {
        [Key]
        public string? ToaXe {  get; set; }
        [DisplayName("Diễn Giải")]
        public string? DienGiai { get; set;}
        public int? LayoutId { get; set; }
        [DisplayName("Nhóm Chỗ")]
        public string? NhomCho {  get; set; }
    }
}

VietNameRailway/VietNameRailway/Models/ErrorViewModel.cs
namespace VietNameRailway.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VietNameRailway/VietNameRailway/Models/Station.cs
using System.ComponentModel;

namespace VietNameRailway.Models
{
    public class Station
    {
        public int Id { get; set; }
        [DisplayName("Mã Ga")]
        public string? MaGa { get; set; }
        [DisplayName("Tên Ga")]
        public string? TenGa { get; set;}
        public string? SKeys { get; set; }
    }
}

VietNameRailway/VietNameRailway/Models/Ticket.cs
using System.ComponentModel;

namespace VietNameRailway.Models
{
    public class Ticket
    {
        public int Id { get; set; }
        public int? DMTauID { get; set; }
        [DisplayName("Loại Chỗ")]
        public string? LoaiCho { get; set; }
        [DisplayName("Tên Loại Chỗ")]
        public string? TenLoaiCho { get; set;}
        public int? GiamGiaTG { get; set; }  
        public int? Thue {  get; set; }
        public int? BaoHiem { get; set; }
        public int? PhiTra {  get; set; }
        [DisplayName("Giá Vé")]
        public int? GiaVe { get; set; }
        public int? GiamGiaPT { get; set; }
        public int? LoaiGiam { get; set;}
        public int? TyLe {  get; set; }
        public string? DienGiai3 {  get; set; }
        public string? DienGiai4 {  get; set; }
        public int? Chos {  get; set; }
    }
}

VietNameRailway/VietNameRailway/Models/Train.cs
using System.ComponentModel;

namespace VietNameRailway.Models
{
    public class Train
    {
        public int Id { get; set; }
        public int? DMTauVatLyId {  get; set; }
        public string? MaGaDi {  get; set; }
        public string? TenGaDi {  get; set; }
        public string? MaGaDen { get; set; }
        public string? TenGaDen { get; set; }
        public int? GaDiKM { get; set; }
        public int? GaDenKM { get; set;}
        public string? NgayDi {  get; set; }
        public string? NgayDen { get; set;}
        [DisplayName("Mác Tàu")]
        public string? MacTau {  get; set; }
        public string? GioDi {  get; set; }
        public string? GioDen { get; set;}
        [DisplayName("Tổng Chỗ Còn")]
        public int? TongChoCon {  get; set; }
        public int? TongChoLock { get; set; }
        public int? TongChoLonger {  get; set; }
        public string? NgayXP { get; set; }
        [DisplayName("Bảng giá vé")]
        public ICollection<Ticket>? BangGiaVes { get; set; }
        public List<int?>? BangGiaVeKeys { get; set; }
        [DisplayName("Toa Xe")]
        public ICollection<TrainCarriage>? ToaXes { get; set; }
        public string? DMTauVatLy { get; set; }
        public string? ListToaP { get; set; }
        public int? Ngay {  get; set; }
        public int? Ngay_XP {  get; set; }
        public int? HanhTrinhID {  get; set; }
        public List<string>? TauXeKeys {  get; set; }
        [DisplayName("Ngày Giờ Đi- Đến")]
        public string? NgayGioDi {  get; set; }
        public string? NgayGioDen { get; set; }
        public string? OnTrainTime {  get; set; }
        public bool HasCheapTicket {  get; set; }=false;
        public string? ListThongBao {  get; set; }

    }
}

VietNameRailway/VietNameRailway/Models/TrainCarriage.cs
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace VietNameRailway.Models
{
    public class TrainCarriage
    {
        public int Id { get; set; }
        public int DMTauVatLyId {  get; set; }
        [DisplayName("Toa Số")]
        public string? ToaSo {  get; set; }
        public int? ToaSoSX {  get; set; }
        public string? ToaXe {  get; set; }
        [DisplayName("Kiểu Toa")]
        public int? ToaXeLayout { get;set; }
        public string? ChoVatLyKeys { get; set; }
        public string? ChoPhuKeys { get; set; }
        public string? ListLoaiCho { get; set; }
        [DisplayName("Mô tả")]
        public string? ToaXeDienGiai { get; set; }
        public string? ToaXeGhiChu { get; set; }
        public int? ToaXeStatus { get; set; }
        public string? NhomChoWeb {  get; set; }

        [DisplayName("Số Chỗ Còn")]
        public int? SoChoCon { get; set; } = 0;
        public int? SoChoLock {  get; set; } = 0;
        public int? SoChoLonger {  get; set; } = 0;
        public int? SoChoKhoa {  get; set; } = 0;
        public int? SoChoTrong {  get; set; } = 0;
    }
}

VietNameRailway/VietNameRailway/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VietNameRailway.Models;

namespace VietNameRailway.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VietNameRailway/VietNameRailway/Controllers/RailwayController.cs
using Microsoft.AspNetCore.Mvc;
using VietNameRailway.Models;
using VietNameRailway.Services;

namespace VietNameRailway.Controllers
{
    public class RailwayController : Controller
    {
        IRailwayService service;
        public RailwayController(IRailwayService service)
        {
            this.service = service;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Station>? list = await service.GetAllGaBacNam();
            return View(list);
        }
        public async Task<IActionResult> ListToa()
        {
            IEnumerable<Carriages> list = await service.GetAllToaXe();
            return View(list);
        }
        public async Task<IActionResult> GetToa()
        {
            Booking? book = await service.SearchTauByGaDiGaDenNgayXP();
            
            return View(book);
        }
    }
}

VietNameRailway/VietNameRailway/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

VietNameRailway/VietNameRailway/Views/Railway/GetToa.cshtml
@model Booking
@{
    Layout = null;
    List<Train> trains = Model.TauDis.ToList();
   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetToa</title>
</head>
<body>
    <h2>Search Chuyen Tau</h2>
    <h3><b>@Html.DisplayNameFor(x=>Model.BookingCode) </b>: @Model.BookingCode</h3>
    <h3><b>@Html.DisplayNameFor(x=>Model.TauDis) </b>: @Model.TauDis.Count</h3>
    <h3><b>@Html.DisplayNameFor(x=>Model.TauVes) </b>: @Model.TauVes</h3>
    <h3><b>@Html.DisplayNameFor(x=>Model.TauVeAlias) </b>: @Model.TauVeAlias</h3>
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(x=>trains.First().Id)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().DMTauVatLy)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().MacTau)</th>
                <th><span style="color:red">@Html.DisplayNameFor(x=>trains.First().TenGaDen)</span> - <span style="color:blue">@Html.DisplayNameFor(x=>trains.First().TenGaDi)</span></th>
                <th>@Html.DisplayNameFor(x=>trains.First().NgayXP)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().Ngay)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().TongChoCon)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().HanhTrinhID)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().ToaXes)</th>
                <th>@Html.DisplayNameFor(x=>trains.First().BangGiaVes)</th>
            </tr>
        </thead>
        <tbody>
            @if (trains.Any())
            {
                @foreach(var item in trains)
                {
                    <tr>
                        <td>@Html.DisplayFor(x=>item.Id)</td>
                        <td><span>@Html.DisplayFor(x=>item.DMTauVatLyId)</span><span>@Html.DisplayFor(x=>item.DMTauVatLy)</span></td>
                        <td>@Html.DisplayFor(x=>item.MacTau)</td>
                        <td><span style="color:red">@Html.DisplayFor(x=>item.TenGaDen)</span> - <span style="color:blue">@Html.DisplayFor(x=>item.TenGaDi)</span></td>
                        <td><span>@Html.DisplayFor(x=>item.NgayDi)</span> - <span>@Html.DisplayFor(x=>item.NgayDen)</span></td>
                        <td>@Html.DisplayFor(x=>item.Ngay)</td>
                        <td>@Html.DisplayFor(x=>item.TongChoCon)</td>
                        <td>@Html.DisplayFor(x=>item.HanhTrinhID)</td>
                        <td>
                            <table>
                                <thead>
                                    <tr>
                                        <th>@Html.DisplayNameFor(x=>item.ToaXes!.First().ToaSo)</th>
                                        <th>@Html.DisplayNameFor(x=>item.ToaXes!.First().ToaXe)</th>
                                        <th>@Html.DisplayNameFor(x=>item.ToaXes!.First().ToaXeLayout)</th>
                                        <th>@Html.DisplayNameFor(x=>item.ToaXes!.First().SoChoCon)</th>
                                        <th>@Html.DisplayNameFor(x=>item.ToaXes!.First().ToaXeDienGiai)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (item.ToaXes!.Any())
                                    {
                                        @foreach(var item2 in item.ToaXes)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(x=>item2.ToaSo)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(x=>item2.ToaXe)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(x=>item2.ToaXeLayout)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(x=>item2.SoChoCon)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(x=>item2.ToaXeDienGiai)
                                                </td>
                                            </tr>
                                        }
                                    }else{
                                        <tr><td colspan="4">No Data</td></tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                        <td>
                            @if (item.BangGiaVes.Any())
                            {
                                <table>
                                    <thead>
                                        <tr>
                                            <th>@Html.DisplayNameFor(x=>item.BangGiaVes.First().LoaiCho)</th>
                                            <th>@Html.DisplayNameFor(x=>item.BangGiaVes.First().TenLoaiCho)</th>
                                            <th>@Html.DisplayNameFor(x=>item.BangGiaVes.First().GiaVe)</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach(var item3 in item.BangGiaVes)
                                        {
                                            <tr>
                                                <td>@Html.DisplayFor(x=>item3.LoaiCho)</td>
                                                <td>@Html.DisplayFor(x=>item3.TenLoaiCho)</td>
                                                <td>@Html.DisplayFor(x=>item3.GiaVe)</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }
                            else
                            {
                                <p>Không có bảng giá vé.</p>
                            }
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="11">No data</td>
                </tr>
            }
        </tbody>
    </table>
</body>
</html>

VietNameRailway/VietNameRailway/Views/Railway/Index.cshtml
@model IEnumerable<Station>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>List Ga Tau</h2>
    <a asp-controller="Railway" asp-action="ListToa">Back To List Toa Tau</a>
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(x=>Model.First().Id)</th>
                <th>@Html.DisplayNameFor(x=>Model.First().MaGa)</th>
                <th>@Html.DisplayNameFor(x=>Model.First().TenGa)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Any())
            {
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x=>item.Id)</td>
                        <td>@Html.DisplayFor(x=>item.MaGa)</td>
                        <td>@Html.DisplayFor(x=>item.TenGa)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</body>
</html>

VietNameRailway/VietNameRailway/Views/Railway/ListToa.cshtml
@model IEnumerable<Carriages>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListToa</title>
</head>
<body>
    <a asp-controller="Railway" asp-action="Index">Back To List Ga Tau</a>
    <h2>List Toa Tau</h2>
    <table>
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(x=>Model.First().ToaXe)</th>
                <th>@Html.DisplayNameFor(x=>Model.First().DienGiai)</th>
                <th>@Html.DisplayNameFor(x=>Model.First().LayoutId)</th>
                <th>@Html.DisplayNameFor(x=>Model.First().NhomCho)</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Any())
            {
                @foreach(var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x=>item.ToaXe)</td>
                        <td>@Html.DisplayFor(x=>item.DienGiai)</td>
                        <td>@Html.DisplayFor(x=>item.LayoutId)</td>
                        <td>@Html.DisplayFor(x=>item.NhomCho)</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</body>
</html>

VietNameRailway/VietNameRailway/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VietNameRailway</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VietNameRailway.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VietNameRailway</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VietNameRailway - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>